### ISSUE TITLE
검색하면 튕깁니다

### ISSUE THREAD

**Issue by jogilsang** [cwpark/ApolloSearch#3]
04-14 09:39:33.590 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102138
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.620 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102139
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.690 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102141
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.700 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102138
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.720 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102429
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.730 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102139
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.730 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102430
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.740 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102141
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.750 16249-18104/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102432
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at lfp.a(PG:20)
                                                          at lef.a(PG:24)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerIntentService.onHandleIntent(PG:24)
                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.760 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102429
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.780 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102430
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
04-14 09:39:33.800 14802-18106/? E/LocalFingerprints: cannot compute fingerprint for: content://media/external/images/media/102432
                                                      java.io.FileNotFoundException: No such file or directory
                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                          at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                          at aryw.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):18)
                                                          at arxg.a(:com.google.android.gms@12521011@12.5.21 (020406-189987672):49)
                                                          at com.google.android.libraries.social.autobackup.FingerprintScannerChimeraIntentService.onHandleIntent(:com.google.android.gms@12521011@12.5.21 (020406-189987672):1)
                                                          at cwk.handleMessage(:com.google.android.gms@12521011@12.5.21 (020406-189987672))
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by cwpark** [comment]
앗 감사합니다. ^^;; ThreeTenABP 초기화를 안했네요.
